### ISSUE TITLE
Confusing Name

### ISSUE THREAD

**Issue by jackmcdade** [transformstudios/statamic-review#1]
Hey there, I love this! Real quick though... I think this addon name is kind of confusing because Statamic already has Drafts (part of the [Revisions](https://statamic.dev/revisions)) feature. What about something more like "Shareable Drafts" or similar?

**Comment by adnankussair** [comment]
@jackmcdade Yea, I can see that being confusing. Either Sharable Drafts or Public Drafts maybe. We'll update this.

**Comment by edalzell** [comment]
Renamed to `Review`
