### ISSUE TITLE
Create new graphics for Statamic marketplace

### ISSUE THREAD

**Issue by adnankussair** [transformstudios/statamic-review#2]

**Comment by edalzell** [comment]
@adnankussair gonna need a logo/something for this. Note the name is now `Review`

**Comment by adnankussair** [comment]
@hollychovan Can you please update the existing Drafts graphic to Review (we had to do a name change) for this plugin. @edalzell needs it to release

**Comment by hollychovan** [comment]
@adnankussair review graphic
![review-plugin-img@2x](https://user-images.githubusercontent.com/59067935/110699988-49572680-81a4-11eb-93fc-22aaf3a92aa2.png)

**Comment by adnankussair** [comment]
@edalzell 

> @adnankussair review graphic
> ![review-plugin-img@2x](https://user-images.githubusercontent.com/59067935/110699988-49572680-81a4-11eb-93fc-22aaf3a92aa2.png)

**Comment by edalzell** [comment]
Released
