### ISSUE TITLE
Addon only compatible with Statamic 3.3.* ?

### ISSUE THREAD

**Issue by doriengr** [transformstudios/statamic-review#24]
**Bug description**

I wanted to use this addon on a site that uses Statamic version 3.2.39. After I created the config file, added the collection handles and the review-fieldtype to my blueprint, I am getting an error.

When I try to open an entry with the corresponding blueprint, I get the following error message:
```
Error
Class "Statamic\Facades\Token" not found
TransformStudios\Review\Fieldtypes\Review::makeUrl
vendor/transformstudios/review/src/Fieldtypes/Review.php:38
```

I can't find the `Token.php` file in the specified vendor folder of my current Statamic version. I looked at Statamic's commit history, and it appears to me that the `Token.php` file was created for Statamic version 3.3. 

Maybe I'm wrong, but it seems like the requirement in Statamic Marketplace is outdated. If this addon should work for lower versions than 3.3, maybe you can give me a hint what I'm doing wrong?

![Bildschirmfoto 2022-11-15 um 10 21 54](https://user-images.githubusercontent.com/57871803/201881469-566e1079-961b-4cb8-a9b4-49274f5a27d2.png)

**Comment by edalzell** [comment]
It only supports 3.3, I've updated it on the marketplace.
