### ISSUE TITLE
[FR] Translatable Button Label

### ISSUE THREAD

**Issue by jakubjo** [transformstudios/statamic-review#30]
It would be great if the button's label would be translatable.

**Comment by edalzell** [comment]
This has been released @jakubjo, please update and check out the readme for instructions

**Comment by jakubjo** [comment]
Thank you, @edalzell for your swift response -- unfortunately it seems it does not work. 

I'm not quite sure how the translations are supposed to be exported to the frontend javascript without rebuilding them? 
I didn't find anything in Laravel's or Statamic's docs.

I think a simpler approach could be sending the backend translated string through the field meta data.
