### ISSUE TITLE
Multisite

### ISSUE THREAD

**Issue by robdekort** [transformstudios/statamic-review#35]
Lovely addon!

However I just noticed it doesn't seem to be possible to get a working link for a translated entry on a multisite environment. Or I'm doing something wrong.

Anyways, thought you'd like to know.

**Comment by edalzell** [comment]
@robdekort to confirm, this is a saved draft entry, right?

**Comment by edalzell** [comment]
I can't replicate this are you able to provide a repo that shows the issue?

**Comment by robdekort** [comment]
Yep it's a saved draft indeed. It was on my own site: https://github.com/studio1902/1902

You'd have to reïnstall the addon though. I only needed it last night :-).

**Comment by edalzell** [comment]
I can't replicate this @robdekort, unless the slugs are different, was that the case with you?

**Comment by edalzell** [comment]
Yup, that's it, your journals have diff slugs in `en`.

Nice find, looking in to it now.

**Comment by edalzell** [comment]
I can't reliably reproduce this issue. Sometimes it produces the wrong URL and sometimes the correct.

If anyone can reliably reproduce, please let me know and I'll get it sorted.

**Comment by robdekort** [comment]
You should be able to reproduce it when cloning my site. It happened every time on the english journal entries.

**Comment by edalzell** [comment]
> You should be able to reproduce it when cloning my site. It happened every time on the english journal entries.

I couldn't make it happen reliably locally, with that site, unfortunately.

**Comment by adnankussair** [comment]
Can't Reproduce. @robdekort If you continue to have issues here, feel free to reopen with additional details regarding being able to reproduce the issue.
