### ISSUE TITLE
Route [statamic.review.show] is missing

### ISSUE THREAD

**Issue by peteger** [transformstudios/statamic-review#36]
Thanks for the lovely addon!

I noticed an issue when selecting the Open Review option from the drop-down. When clicked, it throws a "Route [statamic.review.show] is missing" error.

This is what I've done so far:
1) Installing the addon via `composer require transformstudios/review`
2) Publishing the config via `php artisan vendor:publish --tag=review-config`
3) Editing the config file:
`return [
    'collections' => ["careers", "news", "people", "projects", "thinking", "pages"],
];`
4) Clearing cache, config, restarted php and nginx
5) Edited collection blueprints and added Review URL button (directly, not via fieldset)

Now when I create a new page, disable the Published checkbox and save the draft, I can copy the URL using the Review URL button, but not using the Open Review option from the drop-down. 

This is an excerpt from my composer.json file:

```json
"require": {
        "php": "^8.1",
        "aryehraber/statamic-captcha": "^1.9",
        "fruitcake/laravel-cors": "^2.0.5",
        "guzzlehttp/guzzle": "^7.2",
        "jonassiewertsen/statamic-livewire": "^2.10",
        "laravel/framework": "^9.0",
        "laravel/sanctum": "^2.14",
        "laravel/tinker": "^2.7",
        "statamic/cms": "3.3.68",
        "statamic/seo-pro": "^4.0",
        "transformstudios/review": "^3.8",
        "xndbogdan/statamic-bard-text-color": "^2.4.1"
    },
```

As you can see, we're still running on Statamic is 3.3.68, but I hope it's not a problem.

**Comment by edalzell** [comment]
Oh nice find @peteger, I'll look at this shortly.
