### ISSUE TITLE
Review button grayed out for revisions

### ISSUE THREAD

**Issue by fitzage** [transformstudios/statamic-review#7]
As I started writing this up, I realized there is more going on. There must be something obvious I'm overlooking.

1. When viewing a revision of a current page, the button to copy the review link is grayed out.
2. When viewing a draft of a new page, the button is there and it works, but it has no domain: `undefined/!/review/8862ef57-f977-49ce-8932-7e1c53a2bfc8`

Given this later bit of information, I'm wondering if this could be at all related to me formally having multiple sites set up for localization and yanking it out later, but I'm not finding any other bits still in there.

Some notes:

- APP_URL is set in my .env file, which is usually where the domain info comes from in Statamic.
- I'm using https
- I'm using the plugin on some other sites that work fine

**Comment by adnankussair** [comment]
@fitzage Hmmm.. interesting, we'll look into it as we try to replicate and get back to you.

**Comment by fitzage** [comment]
So I had the review button added to a fieldset. On a whim, I removed it from the fieldset and added it directly to the blueprint.

Now it is no longer grayed out. It works on drafts and reviews. It doesn't include the domain, though, just gives me something like this. This is better than nothing, but there's still something weird going on. `//!/review/fa968f65-1ac8-4485-aa90-56454b717a90`

**Comment by edalzell** [comment]
What’s your site url set to? Show me your sites.php

**Comment by fitzage** [comment]
Ugg, that was the issue now. Still had url set to just /. Now that I set it to pull the app_url from the .env, it works.

I was thrown off partly because of the initial issue of the grayed out button, but this is garden variety config screwup.

**Comment by edalzell** [comment]
We need to update the docs to indicate this must go in a blueprint and not a fieldset

**Comment by edalzell** [comment]
updated simple to put field in blueprint and updated readme to explain
