### ISSUE TITLE
FR: Allow review of protected content

### ISSUE THREAD

**Issue by davidzumini** [transformstudios/statamic-review#8]
Ideally, this would work for content protected by either an `is logged in` tag in the template **or** a Statamic protection scheme, but even just one of the above would be helpful.

**Comment by adnankussair** [comment]
@davidzumini definitely! Will look into adding this and keep you updated on the progress once completed.

**Comment by edalzell** [comment]
Ya I knew this was coming. This won’t be easy.

**Comment by adnankussair** [comment]
@edalzell With some of the recent things we did with "gated content" is this now more feasible?

**Comment by edalzell** [comment]
> @edalzell With some of the recent things we did with "gated content" is this now more feasible?

Nope, cuz our gated stuff requires template code. This is still hard.

**Comment by edalzell** [comment]
Related: https://github.com/statamic/cms/issues/4968

**Comment by edalzell** [comment]
@davidzumini Statamic now supports protected content in Live Preview, this should work in Review now.

If there's still an issue, please re-open.
