### ISSUE TITLE
Addon does not seem to deal with localisation

### ISSUE THREAD

**Issue by JBJannes** [transformstudios/statamic-review#9]
We are using localisation and the review add-on, but the generated review link on the English version is not working. If we generate it via the button it generates the following url:   

`https://[domain].com/en/!/review/fc3aaff0-a401-411c-8e67-3a63c4d94544`   

Which generates a 404.   
If we strip the localisation from the generated url like this:   

`https://[domain].com/!/review/fc3aaff0-a401-411c-8e67-3a63c4d94544`    

The page content of this revision is shown, but global elements are shown in the default language. We meet all requirements, like a filled in `site_url` for both languages, but I think it's something within the sites object:

```
'sites' => [

        'default' => [
            'name' => config('app.name') . '_nl',
            'locale' => 'nl_NL',
            'url' => env('APP_URL', 'https://[domain].com'),
        ],
        'en' => [
            'name' => config('app.name') . '_en',
            'locale' => 'en_US',
            'url' => env('APP_URL', 'https://[domain].com') . '/en',
        ],
    ],
```

Leaving the `/en` part in the localized version changes nothing in the generated url, which feels weird to me. How can we make this work?

- [x] fix generated url
- [x] localized entry data shows
- [ ] localized site data (globals/navs etc) shows

**Comment by edalzell** [comment]
Thanks for pointing this out @JBJannes, we'll take a look at this and get this sorted as soon as we can.

**Comment by edalzell** [comment]
3.1.1 was released and should fix this @JBJannes.
